server:
  port: 8080
logging:
  level:
    com:
      hp:
        warriors:
          mapper: debug
spring:
  application:
    name: warriors-seattle
  datasource:
    seattle:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/warriors-seattle?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
    houston:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/warriors-houston?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
    stock:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/stock?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000  #单位毫秒
#        readTimeout: 10000
iwencai:
  url: http://www.iwencai.com
