server:
  port: 8083
warriors:
  url: www.warriors.com
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  application:
    name: WARRIORS-WEB-BOSTON
  scan:
    base-packages: com.hp.warriors
