server:
  port: 8085
#dubbo:
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    protocol: zookeeper
#  application:
#    name: WARRIORS-WEB-ATLANTA
#  scan:
#    base-packages: com.hp.warriors
spring:
  application:
    name: warriors-atlanta
  datasource:
    seattle:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/warriors-seattle?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
    houston:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/warriors-houston?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
    stock:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/stock?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
iwencai:
  url: http://www.iwencai.com
